### PR TITLE
Folder saving

### PR DESCRIPTION
**Pull request by seabbs**
Hi Seb, 

As per issue #17 I have added support for saving/reading from a folder. Tried to keep additional deps down so the code is different to that posted in the issue (and reflects your split suggestion). Added tests based on those you had already implemented.

New deps are: `stringr` (could be dropped if a work around for `stringr::str_replace` is put in place.

I have also added a Dockerfile with this pull request that replicates the required dev environment. See the automated build [here](https://hub.docker.com/r/seabbs/rbi/builds/). I added this so I could work on this remotely via ssh. In general, I find it to be a real time saver but happy to take out if you wish. If you would like to keep it in I am happy to add to the README explaining the use case (something similar to [this](https://github.com/seabbs/getTBinR)).

### CODE REVIEW

**Comment by seabbs** [comment]
All tests pass locally

**Comment by sbfnk** [comment]
Thanks for the contribution! I've made the following changes:

1) There are (as of very recently) [docker images](https://hub.docker.com/u/sbfnk/) for rbi/libbi. I have now added the corresponding Dockerfiles here. Please remove your Dockerfile from the pull request and, if you need modifications, work on the files in the [docker](https://github.com/sbfnk/RBi/tree/master/docker) directory instead.

2) I've changed this to have a single `name` argument (instead of `file` or `folder`), and to name the files according to the given name (so as to make it easier to associate files with models/projects without needing to know in which directory a file is). So the use would be to say save_libbi("sebs_folder/sebs_model.rds", split=TRUE) creating files "sebs_folder/sebs_model_input.rds", "sebs_folder/sebs_model_output_var1.rds", etc. Does this make sense?

3) I've replaced `str_replace` with `sub` - the code is similar, and we can do away with the `stringr` dependency.

Feel free to add more commits if this doesn't look quite like you had in mind. If it works for you, I'll merge it into the main branch.

**Comment by seabbs** [comment]
That sounds good. I haven't used `sub` before so that is good to know.

Not sure that adding a folder name to every file totally makes sense to me but I can see where you are coming from. From my use I have found having a standardised folder format quite useful. For example if I was coding something to compare an output across lots of model runs having a generic file structure in each folder makes things slightly easier (although of course you can just paste the folder name to the known output).

Great to see the Dockerfiles - I had a bit of a nightmare setting up the one I have been using.

**Comment by sbfnk** [comment]
You should still be able to do that. First model run of model x use `save_libbi(x, “run01/x”, split=TRUE), second run use `save_libbi(x, “run02/x”, split=TRUE)`. For output variable y you’ll then have files `run01/x_output_y.rds` and `run02/x_output_y.rds` - the file structure inside folder `run01` and `run02` will be exactly the same.

Does this make sense?

**Pull request closed without merging**
